# Generated by Django 3.1.7 on 2021-03-24 16:25

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleplus', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('cardtype', models.IntegerField(choices=[(0, 'Big'), (1, 'Small')], default=0)),
                ('thumbnail', models.FileField(blank=True, upload_to=blog.path_rename.path_and_rename)),
                ('intro_pic', models.FileField(blank=True, upload_to=blog.path_rename.path_and_rename_intro)),
                ('intro', models.TextField()),
                ('title', models.CharField(max_length=200, unique=True)),
                ('maintext', models.TextField(default='')),
                ('intro1', models.TextField(blank=True, default='')),
                ('legend', models.TextField(blank=True, default='')),
                ('add_pic', models.FileField(blank=True, upload_to=blog.path_rename.path_and_rename_add)),
                ('ingredients', models.TextField(blank=True, default='')),
                ('preparationtext', models.TextField(blank=True, default='')),
                ('main_pic', models.FileField(blank=True, upload_to=blog.path_rename.path_and_rename_main)),
                ('tip', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_on'],
            },
        ),
    ]
