# Generated by Django 3.1.7 on 2021-03-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210324_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.CharField(choices=[], default='', max_length=200),
        ),
    ]
