# Generated by Django 3.1 on 2021-01-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210104_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='static/img/'),
        ),
    ]
