# Generated by Django 3.1 on 2021-01-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='../static/img'),
        ),
    ]
