# Generated by Django 3.1.7 on 2021-04-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210403_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='cc34f867aa954ac5adcbfdb5317ec545', max_length=200),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='f93ab021b9fe4675a811454415f862ab', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('enjoy the food', 'enjoy the food'), ('uncategorized', 'uncategorized'), ('immunity boosting', 'immunity boosting'), ('our planet', 'our planet')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.CharField(choices=[('mind over matter', 'mind over matter'), ('physical activity', 'physical activity'), ('uncategorized', 'uncategorized')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('enjoy the food', 'enjoy the food'), ('uncategorized', 'uncategorized'), ('immunity boosting', 'immunity boosting'), ('our planet', 'our planet')], default='', max_length=200),
        ),
    ]
