# Generated by Django 3.1 on 2021-01-05 21:59

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210105_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=blog.models.path_and_rename),
        ),
    ]
