# Generated by Django 3.1.7 on 2021-04-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210403_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('enjoy the food', 'enjoy the food'), ('immunity boosting', 'immunity boosting'), ('our planet', 'our planet'), ('uncategorized', 'uncategorized')], default='djangodbmodelsfieldscharfield', max_length=200),
        ),
    ]
