# Generated by Django 3.1 on 2021-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_content2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content2',
            new_name='maintext',
        ),
        migrations.AddField(
            model_name='post',
            name='tip1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='tip2',
            field=models.TextField(default=''),
        ),
    ]
