# Generated by Django 3.1 on 2021-01-11 16:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210111_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_pic',
            field=models.FileField(blank=True, upload_to=blog.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='post',
            name='intro_pic',
            field=models.FileField(blank=True, upload_to=blog.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='post',
            name='main_pic',
            field=models.FileField(blank=True, upload_to=blog.models.path_and_rename),
        ),
    ]
