# Generated by Django 3.1.7 on 2021-04-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210404_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relates_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.CharField(choices=[('animal world', 'animal world'), ('mind over matter', 'mind over matter'), ('physical activity', 'physical activity'), ('uncategorized', 'uncategorized')], default='uncategorized', max_length=200),
        ),
    ]
