# Generated by Django 3.1.7 on 2021-04-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210411_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='relates_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
