# Generated by Django 3.1 on 2021-01-11 16:56

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210111_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_pic',
            field=models.FileField(blank=True, upload_to=blog.models.path_and_rename_add),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro_pic',
            field=models.FileField(blank=True, upload_to=blog.models.path_and_rename_intro),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_pic',
            field=models.FileField(blank=True, upload_to=blog.models.path_and_rename_main),
        ),
    ]
