# Generated by Django 3.1.7 on 2021-04-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210414_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='outro',
            field=models.TextField(blank=True, default=''),
        ),
    ]
