# Generated by Django 3.1 on 2021-01-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210111_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tip1',
            new_name='intro1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tip2',
            new_name='tip',
        ),
    ]
