# Generated by Django 3.1 on 2021-01-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210126_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titleplus',
            field=models.CharField(default='', max_length=200),
        ),
    ]
