# Generated by Django 3.1.7 on 2021-04-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210414_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_pic_desc',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro_pic_desc',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_pic_desc',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='relates_to_desc',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_desc',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
