# Generated by Django 3.1.7 on 2021-04-16 20:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210414_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Contact', 'Contact'), ('enjoy the food', 'enjoy the food'), ('immunity boosting', 'immunity boosting'), ('our planet', 'our planet'), ('uncategorized', 'uncategorized')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='preparationtext',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('Contact', 'Contact'), ('enjoy the food', 'enjoy the food'), ('immunity boosting', 'immunity boosting'), ('our planet', 'our planet'), ('uncategorized', 'uncategorized')], default='', max_length=200),
        ),
    ]
