# Generated by Django 3.1 on 2021-01-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210131_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='legend',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('immunity', 'immunity')], default='', max_length=200),
        ),
    ]
