# Generated by Django 3.1.7 on 2021-04-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210417_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='custom_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
