# Generated by Django 3.1.7 on 2021-04-18 20:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210417_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Enjoy The Food', 'Enjoy The Food'), ('Immunity Boosting', 'Immunity Boosting'), ('Our Planet', 'Our Planet'), ('uncategorized', 'uncategorized')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='maintext',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('Enjoy The Food', 'Enjoy The Food'), ('Immunity Boosting', 'Immunity Boosting'), ('Our Planet', 'Our Planet'), ('uncategorized', 'uncategorized')], default='', max_length=200),
        ),
    ]
