# Generated by Django 3.1.7 on 2021-04-24 11:42

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210423_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cardtype',
        ),
        migrations.AddField(
            model_name='post',
            name='opener_pic',
            field=models.FileField(blank=True, upload_to=blog.models.path_and_rename_opener),
        ),
    ]
