# Generated by Django 3.1.7 on 2021-04-25 15:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_post_cardtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cardtype',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Featured')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.CharField(choices=[('Animal World', 'Animal World'), ('Mind over matter', 'Mind over matter'), ('Physical activity', 'Physical activity'), ('uncategorized', 'uncategorized')], default='uncategorized', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='titleplus',
            field=ckeditor.fields.RichTextField(default='', max_length=240),
        ),
    ]
