# Generated by Django 3.1 on 2021-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210425_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titleplus',
            field=models.TextField(default='', max_length=240),
        ),
    ]
