# Generated by Django 3.1.7 on 2021-04-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20210427_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Enjoy The Food', 'Enjoy The Food'), ('Immunity Boosting', 'Immunity Boosting'), ('Our Planet', 'Our Planet'), ('uncategorized', 'uncategorized')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('Enjoy The Food', 'Enjoy The Food'), ('Immunity Boosting', 'Immunity Boosting'), ('Our Planet', 'Our Planet'), ('uncategorized', 'uncategorized')], default='', max_length=200),
        ),
    ]
