# Generated by Django 3.1.7 on 2021-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20210429_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contibutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('surname', models.CharField(max_length=200, unique=True)),
                ('inactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.CharField(choices=[('Basic Tips', 'Basic Tips'), ('Mind over matter', 'Mind over matter'), ('Physical activity', 'Physical activity'), ('Recipes', 'Recipes'), ('World of animals', 'World of animals'), ('World of humans', 'World of humans'), ('World of plants', 'World of plants'), ('uncategorized', 'uncategorized')], default='uncategorized', max_length=200),
        ),
    ]
