# Generated by Django 3.1.7 on 2021-04-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20210430_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('Dušica', 'Dušica')], default='', max_length=200),
        ),
    ]
