# Generated by Django 3.1.7 on 2021-04-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20210430_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contibutor',
            name='surname',
        ),
    ]
