# Generated by Django 3.1.7 on 2021-05-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_remove_contibutor_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('Dušica Pavlović', 'Dušica Pavlović'), ('Alenka Mestek', 'Alenka Mestek'), ('Jelena Cvetković Š.', 'Jelena Cvetković Š.')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Basics', 'Basics'), ('Enjoy The Food', 'Enjoy The Food'), ('Immunity Boosting', 'Immunity Boosting'), ('Our Planet', 'Our Planet'), ('uncategorized', 'uncategorized')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('Basics', 'Basics'), ('Enjoy The Food', 'Enjoy The Food'), ('Immunity Boosting', 'Immunity Boosting'), ('Our Planet', 'Our Planet'), ('uncategorized', 'uncategorized')], default='', max_length=200),
        ),
    ]
