# Generated by Django 3.1.7 on 2021-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20210502_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='order_count',
        ),
        migrations.AddField(
            model_name='category',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
