# Generated by Django 3.1.7 on 2021-08-14 17:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20210502_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='additionaltext',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('Dušica Pavlović', 'Dušica Pavlović'), ('Alenka Mestek', 'Alenka Mestek'), ('Jelena Cvetković Š.', 'Jelena Cvetković Š.'), ('Igor Šarkanović', 'Igor Šarkanović')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FAQ', 'FAQ'), ('Immunity Boosting', 'Immunity Boosting'), ('Lexicon of plants', 'Lexicon of plants'), ('Lifestyle', 'Lifestyle'), ('Our Planet', 'Our Planet'), ('Recipes', 'Recipes'), ('uncategorized', 'uncategorized')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.CharField(choices=[('Basic Tips', 'Basic Tips'), ('Lexicon of plants', 'Lexicon of plants'), ('Mind over matter', 'Mind over matter'), ('Physical activity', 'Physical activity'), ('Recipes', 'Recipes'), ('World of animals', 'World of animals'), ('World of humans', 'World of humans'), ('uncategorized', 'uncategorized')], default='uncategorized', max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('FAQ', 'FAQ'), ('Immunity Boosting', 'Immunity Boosting'), ('Lexicon of plants', 'Lexicon of plants'), ('Lifestyle', 'Lifestyle'), ('Our Planet', 'Our Planet'), ('Recipes', 'Recipes'), ('uncategorized', 'uncategorized')], default='', max_length=200),
        ),
    ]
