# Generated by Django 3.1.7 on 2021-08-31 19:20

import blog.path_rename
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20210814_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='contibutor',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contibutor',
            name='pic',
            field=models.FileField(blank=True, upload_to=blog.path_rename.path_and_rename_author),
        ),
    ]
