# Generated by Django 3.1.7 on 2021-08-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20210831_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='contibutor',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('Alenka Mestek', 'Alenka Mestek'), ('Dušica Pavlović', 'Dušica Pavlović'), ('Igor Šarkanović', 'Igor Šarkanović'), ('Jelena Cvetković Š.', 'Jelena Cvetković Š.')], default='', max_length=200),
        ),
    ]
