# Generated by Django 3.1 on 2021-09-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20210830_1259'),
        ('blog', '0040_auto_20210831_1945'),
    ]

    operations = [
    ]
