# Generated by Django 3.1.7 on 2021-09-25 22:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_merge_20210914_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='maintext_translated',
        ),
        migrations.AddField(
            model_name='post',
            name='credits',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.CharField(choices=[('Basic Tips', 'Basic Tips'), ('Lexicon of plants', 'Lexicon of plants'), ('Mind over matter', 'Mind over matter'), ('Physical activity', 'Physical activity'), ('Recipes', 'Recipes'), ('World of animals', 'World of animals'), ('World of humans', 'World of humans'), ('uncategorized', 'uncategorized')], default='uncategorized', max_length=200),
        ),
    ]
