# Generated by Django 3.1.7 on 2021-10-16 15:34

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=5)),
                ('titleplus', models.TextField(default='', max_length=240)),
                ('category', models.CharField(choices=[('FAQ', 'FAQ'), ('Immunity Boosting', 'Immunity Boosting'), ('Lexicon of plants', 'Lexicon of plants'), ('Lifestyle', 'Lifestyle'), ('Our Planet', 'Our Planet'), ('Recipes', 'Recipes'), ('uncategorized', 'uncategorized')], default='', max_length=200)),
                ('subcategory', models.CharField(choices=[('Basic Tips', 'Basic Tips'), ('Lexicon of plants', 'Lexicon of plants'), ('Mind over matter', 'Mind over matter'), ('Physical activity', 'Physical activity'), ('Recipes', 'Recipes'), ('World of animals', 'World of animals'), ('World of humans', 'World of humans'), ('uncategorized', 'uncategorized')], default='uncategorized', max_length=200)),
                ('intro', ckeditor_uploader.fields.RichTextUploadingField()),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('maintext', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('intro1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('legend', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('ingredients', ckeditor.fields.RichTextField(blank=True)),
                ('preparationtext', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('additionaltext', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('tip', ckeditor.fields.RichTextField(blank=True, default='')),
                ('outro', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('credits', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
