# Generated by Django 3.1.7 on 2021-10-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_postlang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlang',
            options={'verbose_name_plural': 'Post Languages'},
        ),
    ]
