# Generated by Django 3.1.7 on 2021-10-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20211016_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlang',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
