# Generated by Django 3.1.7 on 2021-10-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20211017_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlang',
            name='cardtype',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Featured')], default=0),
        ),
    ]
