# Generated by Django 3.1.7 on 2021-10-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20211018_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylang',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categorylang',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
