# Generated by Django 3.1.7 on 2021-10-24 18:43

import blog.path_rename
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20211018_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('inactive', models.BooleanField(default=False)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('pic', models.FileField(blank=True, upload_to=blog.path_rename.path_and_rename_author)),
                ('order_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[], default='', max_length=200),
        ),
    ]
