# Generated by Django 3.1.7 on 2021-10-24 19:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_auto_20211024_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('inactive', models.BooleanField(default=False)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('lang', models.CharField(choices=[('de', 'German'), ('en', 'English')], default=0, max_length=5)),
                ('order_count', models.IntegerField(default=0)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.contributor')),
            ],
            options={
                'verbose_name_plural': 'Contributor Languages',
            },
        ),
        migrations.DeleteModel(
            name='Contibutor',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('Alenka Mestek', 'Alenka Mestek'), ('Bor Cvetković Š.', 'Bor Cvetković Š.'), ('Dušica Pavlović', 'Dušica Pavlović'), ('Igor Šarkanović', 'Igor Šarkanović'), ('Jelena Cvetković Š.', 'Jelena Cvetković Š.')], default='', max_length=200),
        ),
    ]
