# Generated by Django 3.1.7 on 2021-03-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210131_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.category')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('immunity', 'immunity'), ('food', 'food'), ('animals', 'animals'), ('plants', 'plants')], default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
            bases=('blog.category',),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childen', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('immunity', 'immunity'), ('food', 'food'), ('animals', 'animals'), ('plants', 'plants')], default='', max_length=200),
        ),
    ]
