# Generated by Django 3.1.7 on 2021-03-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210321_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
    ]
