# Generated by Django 3.1.7 on 2021-03-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210321_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category_ptr',
        ),
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.CharField(choices=[], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Imunity boosting', 'Imunity boosting'), ('Enjoy the food', 'Enjoy the food'), ('Our planet', 'Our planet')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent',
            field=models.CharField(choices=[('Imunity boosting', 'Imunity boosting'), ('Enjoy the food', 'Enjoy the food'), ('Our planet', 'Our planet')], default=1, max_length=200),
        ),
    ]
