# Generated by Django 3.1.7 on 2021-10-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20211018_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlang',
            name='slug',
        ),
    ]
