# Generated by Django 3.1.7 on 2021-10-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_remove_postlang_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlang',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
